/**
 * Measures each client logo in public/logos for the home client grid:
 * `ratio` (width / height) and `ink` (how much of its box is dark, opaque
 * pixels once greyscaled, 0-1). ClientGrid sizes logos from both so heavy
 * block wordmarks and light line marks carry the same visual weight.
 *
 * Run after adding or replacing a logo:  node scripts/measure-logos.mjs
 */
import fs from "node:fs";
import path from "node:path";
import sharp from "sharp";

const dir = "public/logos";
const out = "src/content/logoMetrics.ts";
const rows = [];
for (const file of fs.readdirSync(dir).filter((f) => /\.(webp|png|jpe?g|svg)$/.test(f)).sort()) {
  const { data, info } = await sharp(path.join(dir, file)).ensureAlpha().raw().toBuffer({ resolveWithObject: true });
  let ink = 0;
  for (let i = 0; i < data.length; i += 4) {
    const lum = (0.2126 * data[i] + 0.7152 * data[i + 1] + 0.0722 * data[i + 2]) / 255;
    ink += (data[i + 3] / 255) * (1 - lum);
  }
  ink /= info.width * info.height;
  rows.push(`  "/logos/${file}": { ratio: ${(info.width / info.height).toFixed(3)}, ink: ${ink.toFixed(3)} },`);
}
fs.writeFileSync(
  out,
  `// Generated by scripts/measure-logos.mjs. Do not edit by hand.\n\n/** Per logo: width / height, and dark-pixel coverage of its box (0-1). */\nexport const logoMetrics: Record<string, { ratio: number; ink: number }> = {\n${rows.join("\n")}\n};\n`,
);
console.log(`Wrote ${rows.length} logos to ${out}`);
