import {
  Bot,
  Brain,
  Briefcase,
  Building2,
  Cloud,
  Code,
  Cpu,
  Crown,
  Database,
  FileCheck,
  Gauge,
  Globe,
  Hammer,
  Heart,
  Handshake,
  Layers,
  MessageSquare,
  PenTool,
  RefreshCw,
  Rocket,
  Search,
  Shield,
  Smartphone,
  Sparkles,
  TrendingUp,
  Users,
  Workflow,
  Wrench,
  Zap,
  type LucideProps,
} from "lucide-react";

import type { IconName } from "@/content/types";

const icons = {
  bot: Bot,
  users: Users,
  code: Code,
  rocket: Rocket,
  "refresh-cw": RefreshCw,
  "file-check": FileCheck,
  wrench: Wrench,
  sparkles: Sparkles,
  workflow: Workflow,
  shield: Shield,
  gauge: Gauge,
  layers: Layers,
  brain: Brain,
  building: Building2,
  briefcase: Briefcase,
  crown: Crown,
  handshake: Handshake,
  search: Search,
  "pen-tool": PenTool,
  hammer: Hammer,
  "trending-up": TrendingUp,
  "message-square": MessageSquare,
  database: Database,
  zap: Zap,
  globe: Globe,
  cpu: Cpu,
  cloud: Cloud,
  smartphone: Smartphone,
  heart: Heart,
} satisfies Record<IconName, React.ComponentType<LucideProps>>;

export function Icon({ name, ...props }: { name: IconName } & LucideProps) {
  const Component = icons[name];
  return <Component aria-hidden="true" {...props} />;
}
